### ISSUE TITLE
Crash when opening STL

### ISSUE THREAD

**Issue by kvnper** [smartavionics/Cura#131]
Loading an STL crashes cura.

Using the latest version (released today/yesterday)

![image](https://user-images.githubusercontent.com/47488385/132670729-25eabb50-7def-4ab6-8092-d88327784043.png)

Copy+pasted error text:

**Error Traceback:**

Traceback (most recent call last):
  File "C:\Users\Kevin\AppData\Roaming\cura\master\plugins\CustomJobPrefix\CustomJobPrefix\PrintInformationPatches.py", line 51, in _triggerJobNameUpdate
    self._print_information._updateJobName()
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\UI\PrintInformation.py", line 311, in _updateJobName
  File "C:\Users\Kevin\AppData\Roaming\cura\master\plugins\CustomJobPrefix\CustomJobPrefix\PrintInformationPatches.py", line 57, in _defineAbbreviatedMachineName
    self._print_information._abbr_machine = self._getFormattedPrefix()
  File "C:\Users\Kevin\AppData\Roaming\cura\master\plugins\CustomJobPrefix\CustomJobPrefix\PrintInformationPatches.py", line 72, in _getFormattedPrefix
    return self._abbreviate_name(active_machine_type_name)
  File "C:\Users\Kevin\AppData\Roaming\cura\master\plugins\CustomJobPrefix\CustomJobPrefix\PrintInformationPatches.py", line 106, in _abbreviate_name
    stripped_word = self._print_information._stripAccents(word.upper())
AttributeError: 'PrintInformation' object has no attribute '_stripAccents'

**Logs**

Thread 0x00001d54 (most recent call first):
  File "threading.py", line 306 in wait
  File "C:\Users\Kevin\AppData\Roaming\cura\master\plugins\OctoPrintPlugin\OctoPrintPlugin\python-zeroconf\zeroconf\__init__.py", line 2184 in wait
  File "C:\Users\Kevin\AppData\Roaming\cura\master\plugins\OctoPrintPlugin\OctoPrintPlugin\python-zeroconf\zeroconf\__init__.py", line 1496 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x00004684 (most recent call first):
  File "threading.py", line 306 in wait
  File "C:\Users\Kevin\AppData\Roaming\cura\master\plugins\OctoPrintPlugin\OctoPrintPlugin\python-zeroconf\zeroconf\__init__.py", line 2184 in wait
  File "C:\Users\Kevin\AppData\Roaming\cura\master\plugins\OctoPrintPlugin\OctoPrintPlugin\python-zeroconf\zeroconf\__init__.py", line 1315 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x00005110 (most recent call first):
  File "C:\Users\Kevin\AppData\Roaming\cura\master\plugins\OctoPrintPlugin\OctoPrintPlugin\python-zeroconf\zeroconf\__init__.py", line 1221 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x00000d04 (most recent call first):
  File "D:\Program Files\Ultimaker Cura master v20210908\plugins\USBPrinting\USBPrinterOutputDeviceManager.py", line 87 in _updateThread
  File "threading.py", line 870 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x000040c4 (most recent call first):
  File "threading.py", line 306 in wait
  File "zeroconf\__init__.py", line 2534 in wait
  File "zeroconf\__init__.py", line 1715 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x00004088 (most recent call first):
  File "threading.py", line 306 in wait
  File "threading.py", line 558 in wait
  File "D:\Program Files\Ultimaker Cura master v20210908\plugins\UM3NetworkPrinting\src\Network\ZeroConfClient.py", line 81 in _handleOnServiceChangedRequests
  File "threading.py", line 870 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x000041ec (most recent call first):
  File "zeroconf\__init__.py", line 1369 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x0000222c (most recent call first):
  File "D:\Program Files\Ultimaker Cura master v20210908\plugins\RemovableDriveOutputDevice\RemovableDrivePlugin.py", line 61 in _updateThread
  File "threading.py", line 870 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x000055d0 (most recent call first):
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Backend\Backend.py", line 165 in _storeStderrToLogThread
  File "threading.py", line 870 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x00002530 (most recent call first):
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Backend\Backend.py", line 153 in _storeOutputToLogThread
  File "threading.py", line 870 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x00005b74 (most recent call first):
  File "threading.py", line 302 in wait
  File "threading.py", line 433 in acquire
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x000021b8 (most recent call first):
  File "threading.py", line 302 in wait
  File "threading.py", line 433 in acquire
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x00005378 (most recent call first):
  File "threading.py", line 302 in wait
  File "threading.py", line 433 in acquire
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x00002e70 (most recent call first):
  File "threading.py", line 302 in wait
  File "threading.py", line 433 in acquire
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x00004eb0 (most recent call first):
  File "threading.py", line 302 in wait
  File "threading.py", line 433 in acquire
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x00001ac8 (most recent call first):
  File "threading.py", line 302 in wait
  File "threading.py", line 433 in acquire
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x00005e6c (most recent call first):
  File "threading.py", line 302 in wait
  File "threading.py", line 433 in acquire
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x00004ff8 (most recent call first):
  File "threading.py", line 302 in wait
  File "threading.py", line 433 in acquire
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x00005d54 (most recent call first):
  File "threading.py", line 302 in wait
  File "threading.py", line 433 in acquire
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x00005e74 (most recent call first):
  File "threading.py", line 302 in wait
  File "threading.py", line 433 in acquire
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x00002a10 (most recent call first):
  File "threading.py", line 302 in wait
  File "threading.py", line 433 in acquire
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 98 in _nextJob
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 124 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Thread 0x000036e4 (most recent call first):
  File "serial\serialwin32.py", line 286 in read
  File "serial\serialutil.py", line 659 in read_until
  File "D:\Program Files\Ultimaker Cura master v20210908\plugins\USBPrinting\AutoDetectBaudJob.py", line 76 in run
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\JobQueue.py", line 133 in run
  File "threading.py", line 932 in _bootstrap_inner
  File "threading.py", line 890 in _bootstrap

Current thread 0x00004e18 (most recent call first):
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 396 in _logInfoWidget
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 182 in _createDialog
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 86 in __init__
  File "C:\Users\burto\cura\cura-build\build\inst\bin\cura_app.py", line 195 in exceptHook
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\UI\PrintInformation.py", line 256 in _calculateInformation
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\UI\PrintInformation.py", line 172 in _onPrintDurationMessage
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\UI\PrintInformation.py", line 431 in setToZeroPrintInformation
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\UI\PrintInformation.py", line 444 in _onSceneChanged
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 452 in _show
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Event.py", line 218 in call
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 479 in event
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 1092 in event
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 452 in _show
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Event.py", line 218 in call
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 479 in event
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 1092 in event
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 452 in _show
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Event.py", line 218 in call
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 479 in event
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 1092 in event
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 452 in _show
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Event.py", line 218 in call
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 479 in event
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 1092 in event
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 452 in _show
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Event.py", line 218 in call
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 479 in event
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 1092 in event
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 452 in _show
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Event.py", line 218 in call
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 479 in event
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 1092 in event
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 452 in _show
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Event.py", line 218 in call
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 479 in event
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 1092 in event
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 452 in _show
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Event.py", line 218 in call
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 479 in event
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 1092 in event
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 452 in _show
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Event.py", line 218 in call
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 479 in event
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 1092 in event
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 452 in _show
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Event.py", line 218 in call
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 479 in event
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 1092 in event
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 452 in _show
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Event.py", line 218 in call
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 479 in event
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 1092 in event
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 452 in _show
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Event.py", line 218 in call
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 479 in event
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 1092 in event
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CrashHandler.py", line 452 in _show
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Event.py", line 218 in call
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 479 in event
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 1092 in event
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\UM\Qt\QtApplication.py", line 393 in exec_
  File "C:\Users\burto\cura\cura-build\build\inst\lib\python3.8\site-packages\cura\CuraApplication.py", line 869 in run
  File "C:\Users\burto\cura\cura-build\build\inst\bin\cura_app.py", line 269 in <module>
  File "Console.py", line 36 in run
  File "__startup__.py", line 74 in run

**Comment by kvnper** [comment]
Solved this by deleting that CustomJobPrefix troublesome plugin from the cura configuration folder directory.
